name: Upload Content

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'File to upload'
        required: true
      section:
        description: 'Content section'
        required: true
        default: 'recent'
      title:
        description: 'Content title'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Upload PDF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create content directory if it doesn't exist
        mkdir -p content/${{ github.event.inputs.section }}
        
        # Copy uploaded file to content directory
        cp "${{ github.event.inputs.file }}" "content/${{ github.event.inputs.section }}/"
        
        # Create a metadata file
        echo "{
          \"title\": \"${{ github.event.inputs.title }}\",
          \"filename\": \"$(basename "${{ github.event.inputs.file }}")\",
          \"uploaded_at\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
        }" > "content/${{ github.event.inputs.section }}/$(basename "${{ github.event.inputs.file }}.json")"
        
        # Commit and push changes
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Upload new content: ${{ github.event.inputs.title }}"
        git push
